import * as stylex from "@stylexjs/stylex";

const colors = {
  paper: "#fff",
  line: "#dce2ea",
  blue: "#2563eb",
  soft: "#eff6ff",
  muted: "#64748b",
};

export const common = stylex.create({
  button: {
    font: "inherit",
    color: "inherit",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.line,
    backgroundColor: colors.paper,
    borderRadius: 4,
    padding: "9px 13px",
    cursor: "pointer",
  },
  primary: {
    backgroundColor: colors.blue,
    color: "#fff",
    borderColor: colors.blue,
    textDecoration: "none",
  },
  eyebrow: {
    textTransform: "uppercase",
    letterSpacing: "0.13em",
    fontSize: 11,
    fontWeight: 600,
    color: colors.blue,
    margin: "0 0 7px",
  },
  muted: { color: colors.muted },
  error: {
    color: "#92352f",
    backgroundColor: "#fff0ee",
    padding: 10,
    borderRadius: 4,
  },
  brandMark: {
    width: 32,
    height: 32,
    display: "grid",
    placeItems: "center",
    borderRadius: 4,
    backgroundColor: colors.blue,
    color: "#fff",
    font: "700 22px system-ui, sans-serif",
  },
  label: {
    display: "grid",
    gap: 6,
    fontSize: 12,
    fontWeight: 600,
    margin: "12px 0",
  },
  control: {
    font: "inherit",
    fontSize: 13,
    fontWeight: 400,
    color: "inherit",
    width: "100%",
    borderWidth: 1,
    borderStyle: "solid",
    borderRadius: 4,
    backgroundColor: "#fff",
    padding: 10,
    outlineStyle: "none",
    borderColor: { default: colors.line, ":focus": colors.blue },
    boxShadow: { default: null, ":focus": `0 0 0 3px ${colors.soft}` },
  },
  textarea: { minHeight: 110 },
  danger: { color: "#9a3c3c", backgroundColor: "transparent", borderWidth: 0 },
  heading: { fontSize: 26, fontWeight: 650, margin: "0 0 8px" },
  notice: {
    backgroundColor: colors.soft,
    color: "#1e40af",
    borderRadius: 4,
    padding: 14,
    fontSize: 13,
    lineHeight: 1.6,
  },
  warning: { backgroundColor: "#fffbeb", color: "#92400e" },
  badge: {
    backgroundColor: "#fef3c7",
    color: "#92400e",
    borderRadius: 20,
    padding: "4px 10px",
    fontSize: 12,
    whiteSpace: "nowrap",
  },
  live: { backgroundColor: "#dcfce7", color: "#166534" },
  dialog: {
    width: "min(560px, calc(100vw - 32px))",
    maxHeight: "calc(100vh - 32px)",
    overflow: "auto",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.line,
    borderRadius: 6,
    backgroundColor: { default: colors.paper, "::backdrop": "#0f172a66" },
    color: "#182235",
    padding: 28,
    boxShadow: "0 20px 70px #0f172a33",
  },
});
